FROM node:20-alpine AS build

WORKDIR /app

COPY package.json ./
RUN corepack enable && pnpm install

COPY . .

RUN corepack enable && pnpm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
